#!/bin/sh

LOCALPATH=${REQUEST_URI##${SCRIPT_NAME}/}
COMMAND=${LOCALPATH%/}


case $COMMAND in
  on|off|status|debug)
    echo "Status: 200 OK"
    echo "Content-Type: text/plain"
    echo
    coffee-control $COMMAND
    ;;
  *)
    echo "Status: 400 Bad Request"
    echo "Content-Type: text/plain"
    echo
    echo "Bad request, change your URL"
esac
